theme = "catppuccin_mocha"

[editor]
line-number = "relative"
bufferline = "multiple"
cursorline = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false

[keys.normal]
C-g = ":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w80% -h80% -E lazygit"
esc = ["collapse_selection", "keep_primary_selection"]
C-f = [":new", ":insert-output lf-pick", ":theme default", "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!", ":theme tokyonight_storm"]
# j = "move_char_left"
# k = "move_line_down"
# l = "move_line_up"
# ";" = "move_char_right"
# h = "collapse_selection"
# A-h = "flip_selections"

# A-j = "select_prev_sibling"
# A-k = "shrink_selection"
# A-l = "expand_selection"
# "A-;" = "select_next_sibling"

# [keys.normal.z]
# k = "scroll_down"
# l = "scroll_up"

# [keys.normal.g]
# j = "goto_line_start"
# ";" = "goto_line_end"

# [keys.normal.C-w]
# j = "jump_view_left"
# C-j = "jump_view_left"
# k = "jump_view_down"
# C-k = "jump_view_down"
# l = "jump_view_up"
# C-l = "jump_view_up"
# ";" = "jump_view_right"
# "C-;" = "jump_view_right"


# [keys.select]
# j = "extend_char_left"
# k = "extend_line_down"
# l = "extend_line_up"
# ";" = "extend_char_right"
# h = "collapse_selection"
# A-h = "flip_selections"

# A-j = "select_prev_sibling"
# A-k = "shrink_selection"
# A-l = "expand_selection"
# "A-;" = "select_next_sibling"

# [keys.select.z]
# k = "scroll_down"
# l = "scroll_up"

# [keys.select.g]
# j = "goto_line_start"
# ";" = "goto_line_end"

# [keys.select.C-w]
# j = "jump_view_left"
# C-j = "jump_view_left"
# k = "jump_view_down"
# C-k = "jump_view_down"
# l = "jump_view_up"
# C-l = "jump_view_up"
# ";" = "jump_view_right"
# "C-;" = "jump_view_right"
